version: "3.9"

services:
  web:
    build: ./php
    container_name: rolltor_web
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped

  db:
    image: mariadb:11
    container_name: rolltor_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: rolltor
      MYSQL_USER: rolltor_user
      MYSQL_PASSWORD: rolltor_pass
      TZ: Europe/Berlin
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: rolltor_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: rolltor_user
      PMA_PASSWORD: rolltor_pass
      UPLOAD_LIMIT: 50M

volumes:
  db_data:
